language: node_js
node_js:
  - "6"
addons:
  - "chrome": "stable"
install:
  - "npm install"
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
  - "npm run start &"
  - "sleep 3"
script:
  - "npm run jshint"
  - "npm run karma"
  - "npm run webdriver-update"
  - "npm run protractor"
